language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
env:
  - "HARNESS_VERBOSE=1"
script: prove -vl
install:
  - "cpanm -n Text::Markdown Mojolicious Mojo::Base Test::Spec Mojolicious::Plugin::Authentication File::Copy"
notifications:
  email: false
